project/urls.py
import os

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from swc.views import (UpcomingBootcamps, EventDetail, EditProfile,
        ProfileView, AddTimeChunk, DeleteTimeChunk, TimeChunkData)

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^profile/edit/$',
        login_required(EditProfile.as_view()), name='profile_edit'),

    url(r'^profile/(?P<pk>\d+)/',
        ProfileView.as_view(), name='profile_view'),

    url(r'^profile/$',
        ProfileView.as_view(), name='profile_view_user'),

    url(r'^profile/calendar/$', 'swc.views.calendar',
        kwargs={'target': 'user'},
        name="person_calendar_edit"),

    url(r'^bootcamps/upcoming/', UpcomingBootcamps.as_view(),
        name='bootcamps_upcoming'),

    url(r'^bootcamps/(?P<pk>\d+)/(?P<slug>[-\w\d]+)', EventDetail.as_view(),
        name='event_detail'),

    url(r'^bootcamps/(?P<pk>\d+)/', EventDetail.as_view(),
        name='event_detail_id'),

    url(r'^dates/add/$', AddTimeChunk.as_view(), name='dates_add'),

    url(r'^dates/data/(?P<source>[-\d\w]+)/(?P<pk>\d+)/$',
        TimeChunkData.as_view(), name='calendar_data'),
    url(r'^dates/delete/$', DeleteTimeChunk.as_view(), name='dates_delete'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        name='logout'),

    url(r'^manage/', include(admin.site.urls)),

    url(r'', include('social_auth.urls')),

    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
)

if 'production' not in os.environ['DJANGO_SETTINGS_MODULE']:
    urlpatterns += staticfiles_urlpatterns()

swc/models.py
from __future__ import unicode_literals

import datetime

from django.db import models

from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse

from jsonfield import JSONField
from model_utils import Choices
from model_utils.managers import QueryManager


class GeoLocation(models.Model):
    """
    An abstract class to house geographic info
    """
    # raw geocode data from google API
    geodata = JSONField(blank=True)
    country = models.CharField(max_length=50, blank=True)
    country_short = models.CharField(max_length=2, blank=True)
    lat = models.FloatField(null=True, blank=True)
    long = models.FloatField(null=True, blank=True)
    # the google geocode type resolution
    geo_type = models.CharField(max_length=40, blank=True)
    # the SWC notion of bootcamp regions, determined from country
    region = models.CharField(max_length=40, blank=True)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class SWCPerson(GeoLocation):
    user = models.OneToOneField(User, related_name="profile", null=True,
            blank=True)
    name1 = models.CharField(max_length=80)
    name2 = models.CharField(max_length=80, blank=True)
    bio = models.TextField(blank=True)
    # TODO fields to consider
    # organizational affiliation
    # contact_phone = models.TextField(blank=True)
    # URL
    profile_email = models.EmailField(max_length=254, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "People"

    @classmethod
    def get_for_user(self, user):
        if user.id:  # a saved user
            obj, created = self.objects.get_or_create(
                    user=user,
                    defaults={'profile_email': user.email}
                    )
            return obj
        return None

    def __str__(self):
        return "{} {}".format(self.name1, self.name2)

    def get_absolute_url(self):
        return reverse('profile_view', kwargs={'pk': self.id})

    @property
    def email(self):
        if self.profile_email:
            return self.profile_email
        if self.user and self.user.email:
            return self.user.email
        return None


@python_2_unicode_compatible
class SWCEvent(GeoLocation):
    TYPES = Choices('bootcamp', 'training')
    REGISTRATIONS = Choices(
            'open',
            'restricted',
            'full',
            'pending',
            'closed',
            'proposed',
            )

    type = models.CharField(choices=TYPES, default=TYPES.bootcamp,
            max_length=50)
    # location
    start_date = models.DateField()
    end_date = models.DateField()
    human_times = models.CharField(verbose_name="Event Times",
            default="9AM to 4:30PM", max_length=50)
    venue = models.TextField(blank=True)
    registration = models.CharField(choices=REGISTRATIONS,
            default=REGISTRATIONS.proposed, max_length=40)
    capacity = models.IntegerField(default=40)
    home_page = models.URLField(blank=True)
    participants = models.ManyToManyField(SWCPerson, through='Participant')

    objects = models.Manager()
    upcoming = QueryManager(start_date__gte=datetime.date.today())
    open = QueryManager(
            start_date__gte=datetime.date.today(),
            registration='open',
            )

    class Meta:
        unique_together = (("start_date", "venue"),)
        ordering = ['start_date']

    @property
    def slug(self):
        return self.__str__()

    def __str__(self):
        return "{}-{}".format(self.start_date, self.venue)


@python_2_unicode_compatible
class Participant(models.Model):
    ROLES = Choices('instructor', 'helper', 'host', 'student')
    event = models.ForeignKey(SWCEvent)
    person = models.ForeignKey(SWCPerson, related_name='participation_set')
    role = models.CharField(choices=ROLES, default=ROLES.student,
            max_length=40)
    # confirmed can be used to track whether the participant affirmed a
    # reminder sent x days before event
    confirmed = models.BooleanField(default=False,
            help_text="Has the participant verified they will be attending?")
    attended = models.BooleanField(default=False,
            help_text="Did the participant show up?")
    completed = models.BooleanField(default=False,
            help_text="Did the participant remain and complete the event?")

    def __str__(self):
        return '{}-{}-{}'.format(self.event, self.person, self.role)


class TimeChunk(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    event = models.ForeignKey(SWCEvent, related_name="start_ranges",
            blank=True, null=True)
    person = models.ForeignKey(SWCPerson, related_name="available_dates",
            blank=True, null=True)

swc/forms.py
import json
import jingo.monkey
jingo.monkey.patch()
from django import forms
from .models import SWCPerson


class ProfileForm(forms.ModelForm):
    new_geo = forms.CharField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = SWCPerson
        fields = ['name1', 'name2', 'bio', 'profile_email']
        labels = {
                'name1': "First/Given Name",
                'name2': "Last/Family/Surname Names",
                }

    class Media:
        js = ['https://maps.googleapis.com/maps/api/js?sensor=false',
                'js/bootstrap/bootstrap-typeahead.js',
                'js/jquery.addresspicker.js',
                'js/jquery.json-2.4.min.js',
             ]

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(ProfileForm, self).save(commit=False)
        if self.cleaned_data['new_geo']:
            m.geodata = json.loads(self.cleaned_data['new_geo'])
            # TODO extract fields from this blob
            m.geo_type = m.geodata['geometry']['location_type']
            m.lat = m.geodata['lat_val']
            m.long = m.geodata['long_val']
            for comp in m.geodata['address_components']:
                if 'country' in comp['types']:
                    m.country = comp['long_name']
                    m.country_short = comp['short_name'].lower()
                    break
        if commit:
            m.save()
        return m

swc/views.py
import datetime

from dateutil.parser import parse

from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, UpdateView, View
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

from braces.views import JSONResponseMixin

from .models import SWCEvent, SWCPerson, TimeChunk
from .forms import ProfileForm


class EventList(ListView):
    model = SWCEvent
    template_name = 'bootcamp_list.html'


class UpcomingBootcamps(EventList):
    def get_queryset(self):
        return self.model.upcoming.filter(type='bootcamp')


class EventDetail(DetailView):
    model = SWCEvent
    context_object_name = 'event'
    template_name = "event_detail.html"


# note login_required applied at URL
class EditProfile(UpdateView):
    model = SWCPerson
    form_class = ProfileForm
    template_name = 'profile_edit.html'
    context_object_name = 'profile'

    def get_object(self):
        return SWCPerson.get_for_user(self.request.user)


class ProfileView(DetailView):
    model = SWCPerson
    fields = ['name1']
    template_name = 'profile_detail.html'
    context_object_name = 'profile'

    def get_object(self):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        if pk is None:
            return SWCPerson.get_for_user(self.request.user)
        return super(ProfileView, self).get_object()


@login_required
def calendar(request, target='user'):
    if target == 'user':
        target_pk = 0
    else:
        # TODO get event pk
        target_pk = 0
    return render(request, "calendar_view.html", {
        'target': target,
        'target_pk': target_pk,
        })


class AddTimeChunk(JSONResponseMixin, View):
    http_method_names = [u'post']

    # TODO needs auth checks
    def post(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
            raise PermissionDenied
        # TODO convert to UTC?? only needed for dateline regions?
        start = parse(self.request.POST.get('start'))
        end = parse(self.request.POST.get('end'))
        create_kwargs = {'start_date': start.date(), 'end_date': end.date()}
        if self.request.POST.get('target') == 'user':
            person = SWCPerson.get_for_user(self.request.user)
            create_kwargs['person'] = person
        elif 'event-' in self.request.POST.get('target'):
            # target specified as 'event-<event pk>'
            pk = self.request.POST.get('target').split('-')[1]
            event = SWCEvent.objects.get(pk=pk)
            create_kwargs['event'] = event
        chunk, created = TimeChunk.objects.get_or_create(**create_kwargs)
        return self.render_json_response({"msg": "OK", "eventid": chunk.id})


class DeleteTimeChunk(JSONResponseMixin, View):
    http_method_names = [u'post']

    def post(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
            raise PermissionDenied
        # TODO all kinds of permission checking go here
        pk = self.request.POST.get('eventid').split('-')[1]
        chunk = TimeChunk.objects.get(pk=int(pk))
        if chunk.person:
            if chunk.person.user.id == self.request.user.id:
                chunk.delete()
            else:
                raise PermissionDenied
        elif chunk.event:
            # TODO check if owner
            pass

        return self.render_json_response({"msg": "OK"})


class TimeChunkData(JSONResponseMixin, View):
    http_method_names = [u'get']

    def get(self, *args, **kwargs):
        start_date_range = datetime.datetime.utcfromtimestamp(
                int(self.request.GET.get('start'))).date()
        end_date_range = datetime.datetime.utcfromtimestamp(
                int(self.request.GET.get('end'))).date()
        if kwargs['source'] == 'user':
            person = SWCPerson.get_for_user(self.request.user)
            chunks = TimeChunk.objects.filter(
                    person=person,
                    start_date__gte=start_date_range).filter(
                    start_date__lte=end_date_range)  # nopep8
        else:
            # TODO event source
            pass
        data = [{"start": c.start_date,
                "end": c.end_date,
                "id": "event-{}".format(c.id),
                "title": "event-{}".format(c.id),
                } for c in chunks]
        return self.render_json_response(data)

swc/templates/_base.html
<!DOCTYPE html>
<html>

{% macro youtube(title, stem, time) -%}
  <div class="youtube">
    <iframe title="{{title}}"
            src="http://www.youtube.com/embed/{{stem}}"
            time="{{time}}"
            width="640" height="506"
            frameborder="0"
            allowfullscreen="allowfullscreen"></iframe>
  </div>
{%- endmacro %}

{% macro disqus(title, ident) -%}
<div id="disqus_thread"></div>
<script type="text/javascript">
  var disqus_shortname = 'software-carpentry';
  var disqus_developer = 1;
  var disqus_identifier = '{{ident}}';
  var disqus_title = '{{title}}';
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{%- endmacro %}

{% macro navhighlight(section) -%}
<script type="text/javascript">
  var nav = document.getElementById('nav-{{section}}');
  if (nav.className) {
    nav.className = nav.className + ' active';
  } else {
    nav.className = 'active';
  }
</script>
{%- endmacro %}

{% macro list_badges(badge_kind, people) -%}
<div style="clear:both; bottom-margin:30px;">
<ul>
  {% for name, user, site in people %}
  <div class="pull-left" style="width:175px;">
  <li><a badge-kind="{{badge_kind}}"
         badge-user="{{user}}"
         {% if site %}
         href="{{site}}">
         {% else %}
         href="{{page.root}}/about/team.html#{{user}}">
         {% endif %}
         {{name}}</a></li>
  </div>
  {% endfor %}
</ul>
</div>
<div style="clear:both;"></div>

{%- endmacro %}

{% macro badge_issuing() -%}
<!-- attach actions -->
<script src="http://beta.openbadges.org/issuer.js"></script>
<script type="text/javascript">
  window.onload = function () {
    $('a[badge-kind]').click(function (e) {
      e.preventDefault();
      var kind = $(this).attr('badge-kind');
      var user = $(this).attr('badge-user');
      var link = $(this).attr('href');

      // configure dialog
      var assertionURL = "{{site}}/badges/"+kind+"/"+user+".json";
      $('#assertion-modal iframe').attr('src', assertionURL);
      $('#assertion-modal button[name=add]').click(function(e) {
        OpenBadges.issue([assertionURL]);});
      $('#modal-badge-img').attr("src", "{{site}}/img/badges/"+kind+".png");
      $('#assertion-modal div.modal-footer a').attr("href", link);
      $('#assertion-modal').modal('show');
      return false;
    });
  };
</script>

<!-- Model dialog for the assertion -->
<div id="assertion-modal" class="modal hide fade" role="dialog">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Badge Details</h3>
  </div>
  <div class="modal-body">
    The following blob (known as an <a
    href="https://github.com/mozilla/openbadges/wiki/Assertions">assertion</a>)
    certifies the work done for this badge. If this is your badge, you may add
    it to your Mozilla Backpack.
    <iframe src=""></iframe>
    <img id="modal-badge-img" src=""/>
  </div>
  <div class="modal-footer">
    <a class="pull-left" href="{{site}}/about/team.html">More about this person</a>
    <button class="btn" name="add">Add badge to my Backpack</button>
    <button class="btn" data-dismiss="modal">Close</button>
  </div>
</div>
{%- endmacro %}

  <head>
    <link rel="shortcut icon" type="image/x-icon" href="{{page.root}}/favicon.ico" />
    {% block css %}
    <link href="{{page.shared}}/css/bootstrap/bootstrap.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{{page.shared}}/css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{{page.root}}/bc/css/swc.css" />
    <link rel="stylesheet" type="text/css" href="{{page.root}}/bc/css/swc-bootstrap.css" />
    <link rel="alternate" type="application/rss+xml" title="The Software Carpentry Blog" href="{{site.site}}/feed.xml"/>
    <meta http-equiv="last-modified" content="{{site.timestamp}}" />
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% endblock css %}
    {% block metadata %}{% endblock metadata %}
    {% block file_metadata %}{% endblock file_metadata %}
    {% block pagetitle %}<title>Software Carpentry: {{page.title}}</title>{% endblock pagetitle %}
    {% block javascript %}{% endblock javascript %}
  </head>

  <body {%- block onload %}{% endblock onload -%} >
    <div class="container shadow">

      <div class="banner">
        <a href="{{page.root}}/index.html" title="Software Carpentry Home">
          <img src="{{page.shared}}/img/logos/software-carpentry-banner.png" alt="Software Carpentry banner" />
        </a>
      </div>

      {% include "navbar.html" %}
      {% block navhighlight %}{% endblock navhighlight %}

      <div class="row-fluid">
        <div class="span10 offset1">
        {% block title %}
        <h1 class="title">{{ page.title }}</h1>
        {% endblock title %}
        {% block details %}{% endblock details %}
	{% block files %}{% endblock files %}
        <!-- start content -->
        {% block content %}{% endblock content %}
        <!-- end content -->
        {#
        {% block comments %}{{disqus(page.title, page.path)}}{% endblock comments %}
        #}
        </div>
      </div>

      {% include "footer.html" %}
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="{{page.root}}/js/bootstrap/bootstrap.min.js"></script>
    {% block pagejs%}{% endblock %}
    <!-- Google Analytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37305346-1']);
      _gaq.push(['_setDomainName', 'software-carpentry.org']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>

swc/templates/bootcamp_list.html
{% extends "_base.html" %}
{% block pagetitle %}<title>Bootcamps</title>{% endblock pagetitle %}


{% block content %}
<h1>Upcoming Bootcamps:</h1>

<ul>
    {% for camp in object_list %}
    <li><a href="{{ url('event_detail_id', pk=camp.pk) }}{{ camp.slug }}">{{ camp.venue }} {{ camp.start_date }}</a></li>
    {% endfor %}
</ul>

{% endblock content %}

swc/templates/calendar_test.html
{% extends "_base.html" %}
{% block css%}
{{ super() }}
 <link href="{{page.shared}}/fullcalendar/fullcalendar.css" rel="stylesheet" />
 <link href="{{page.shared}}/fullcalendar/fullcalendar.print.css" rel="stylesheet" />
{% endblock css %}

{% block pagetitle %}<title>Profile Edit</title>{% endblock pagetitle %}
{% block content %}
<h2>calendar</h2>
<div id='calendar'></div>
{% endblock content %}

{% block pagejs %}
{{ super() }}
    <script src="{{page.root}}/fullcalendar/fullcalendar.min.js"></script>
    <script src="{{page.root}}/fullcalendar/jquery-ui-1.10.2.custom.min.js"></script>
    <script type="text/javascript">

$(document).ready(function() {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var csrftoken = getCookie('csrftoken');

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // page is now ready, initialize the calendar...
    var calendar = $('#calendar').fullCalendar({
                selectable: true,
                editable: true,
                selectHelper: true,
                select: function(start, end, allDay) {
                    console.log(start, end, allDay);
                    $.post("{{ url('dates_add')}}",
                        {start:start, end:end, target:"{{ target }}"},
                        function(data) {
                        console.log(data);
                        if (data.msg == "OK") {
                            var e = calendar.fullCalendar('renderEvent', {
                                    title: 'event-' + data.eventid,
                                    start: start,
                                    end: end,
                                    allDay: allDay,
                                    id: 'event-' + data.eventid,
                                },
                                true // make the event "stick"
                            );
                            console.log(e);
                            calendar.fullCalendar('unselect');
                        }
                        }
                    )
                },
                eventAfterRender: function( event, element, view ) {
                    element.popover({
                        title: "Delete Availability",
                        content: '<button class="btn btn-danger delete-button ' + event.id + '"><i class="icon-remove-sign icon-white"></i> | Delete ' + event.id + '</button',
                        placement: 'bottom',
                        html: true,
                        trigger: 'manual',
                        });
                  },
                   eventClick: function(calEvent, jsEvent, view) {
                        $('.fc-event').not(this).popover('hide');
                        $('.fc-event').each(function(index, obj) {
                                if ($(obj).prop("id") != $(this).prop("id")) {
                                    }
                                });
                        $(this).popover('show');
                    }


    }); //end calendar


    $('body').on('click', '.popover button', function (e) {
        // handle the delete button click, and delete corresponding cal event
        // see also: http://stackoverflow.com/questions/13205103/attach-event-handler-to-button-in-twitter-bootstrap-popover
            var eventid = $(this).attr('class').split(/\s+/).pop();
            console.log(eventid);
            $.post("{{ url('dates_delete')}}", {eventid:eventid},
                    function(data) {
                        if (data.msg == "OK") {
                            console.log('delete ok')
                            calendar.fullCalendar('removeEvents', eventid);
                            }
                        });


})
});
    </script>
{% endblock pagejs %}

swc/templates/event_detail.html
{% extends "_base.html" %}
{% block pagetitle %}<title>Bootcamps</title>{% endblock pagetitle %}


{% block content %}

<h2>{{ event }}</h2>

{% endblock content %}

swc/templates/footer.html
<div class="footer">
  <a class="label swc-blue-bg" href="{{site.facebook_url}}">Facebook</a>
  <a class="label swc-blue-bg" href="{{site.google_plus_url}}">Google+</a>
  <a class="label swc-blue-bg" href="{{site.twitter_url}}">Twitter</a>
  <a class="label swc-blue-bg" href="{{site.github_url}}">GitHub</a>
  <a class="label swc-blue-bg" href="{{site.rss_url}}">RSS</a>
  <a class="label swc-blue-bg" href="{{page.root}}/license.html">License</a>
  <a class="bugreport label swc-blue-bg" href="mailto:{{site.contact}}?subject=bug%20in%20{{page.path}}">Bug Report</a>
</div>

swc/templates/profile_detail.html
{% extends "_base.html" %}
{% block css%}
{{ super() }}
 <link href="{{page.shared}}/css/flags.css" rel="stylesheet" />
{% endblock %}

{% block pagetitle %}<title>Profile</title>{% endblock pagetitle %}
{% block content %}
{% if user.id == profile.user.id %}
    <a href="{{ url('profile_edit')}}">Edit your profile</a>
{% endif %}
        {% if profile.email %}
            {{ gravatar(profile.email) }}
        {% endif %}
        {% if profile.country %}
        <img id="country-flag" src="{{page.shared}}/img/blank.gif"
        class="flag flag-{{ profile.country_short }}" alt="{{ profile.country }}"
         />
        {% endif %}

{{ profile.name1 }}
{% endblock content %}

swc/templates/profile_edit.html
{% extends "_base.html" %}
{% block css%}
{{ super() }}
{{ form.media.css }}
 <link href="{{page.shared}}/css/flags.css" rel="stylesheet" />
{% endblock %}

{% block pagetitle %}<title>Profile Edit</title>{% endblock pagetitle %}
{% block content %}

<a href="{{ url('person_calendar_edit') }}">Edit my Availability</a>
<form action="" method="post">
    {{ csrf() }}

    {{ form }}
    <div class="well">
        <label>Location: <i>(you may enter city name, airport, or full address)</i></label>

        <img id="country-flag" src="{{page.shared}}/img/blank.gif"
        {% if profile.country %}
        class="flag flag-{{ profile.country_short }}" alt="{{ profile.country }}"
        {% endif %}
         />

        <input id="addresspicker_map"  autocomplete="off" value="{{ profile.geodata.formatted_address }}" />
        <div style="width:300px;height:300px;margin-top:20px">
            <div id="map_canvas" style="width:100%; height:100%"></div>
            <div id="location" class=""></div>
        </div>
    </div>

    <input type="submit" value="Submit" />
</form>


{% endblock content %}

{% block pagejs %}
{{ super() }}
{{ form.media.js }}
<script type="text/javascript" charset="utf-8">
    // This script is inline for template expansion
    $(document).ready(function() {
        var addresspicker = $( "#addresspicker" ).addresspicker();
        var addresspickerMap = $( "#addresspicker_map" ).addresspicker(
        {
            regionBias: "de",
            map:      "#map_canvas",
            typeaheaddelay: 1000,
            mapOptions: {
                zoom:16,
                center: new google.maps.LatLng(
                    {{ profile.lat|default('43.6481', true) }},
                    {{ profile.long|default('-79.4042', true) }}
                    )
            }

        });

        addresspickerMap.on("addressChanged", function(evt, address) {
            // add the lat long to the JS obj - because the mapping names
            // are minimized, and the JS class has special methods
            address.lat_val = address.geometry.location.lat();
            address.long_val = address.geometry.location.lng();
            $('#id_new_geo').val($.toJSON(address));
            // extract the country and update flag graphic
            var countryCode;
            $.each(address.address_components, function(index, value){
                if (value.types.indexOf('country') >= 0) {
                    countryCode = value.short_name.toLowerCase();
                }
                });
            $('#country-flag').attr('class', 'flag flag-' + countryCode);

        });
        addresspickerMap.on("positionChanged", function(evt, markerPosition) {
            markerPosition.getAddress( function(address) {
                if (address) {
                    $( "#addresspicker_map").val(address.formatted_address);
                }
            })
        });
    });
</script>
{% endblock %}